#!/bin/bash
cd E1_trans_lsj
for z in 22 23 24
do
        for i in  3 4 5 
        do 
        cp ../../gs/BP/2Po-${i}-${z}-bp.c .
        cp ../../gs/BP/2Po-${i}-${z}-bp.w .
        cp ../../gs/BP/2Po-${i}-${z}-bp.j .
        cp ../../es/BP/2Se-${i}-${z}-bp.c .
        cp ../../es/BP/2Se-${i}-${z}-bp.w .
        cp ../../es/BP/2Se-${i}-${z}-bp.j .
biotr << end
2Po-${i}-${z}-bp
2Se-${i}-${z}-bp
n
y
c
E1
*
end
done
done
rm fort.* *.c *.w *.j
